config/routes.rb
Rails.application.routes.draw do
  
  get 'friend/list' => "friend#list"

  get 'friend/add/:id' => "friend#add"
  post 'friend/add' => "friend#addByPost" #too bad, how can I merge 2 routers?

  get 'friend/block/:id' => "friend#block"
  get 'block/list' => "friend#blockList"

  get 'inbox' => "message#inbox"
  get 'inbox/:id' => "message#detail"

  get 'send' => "message#sendMessage"
  post 'send' => "message#sendTo"

  get 'login' => "session#new"
  post 'login' => "session#create"
  get 'signout' => "session#destroy"

  get 'signup' => "user#show"
  post 'signup' => "user#signup"
  

  root to: 'session#new'

end

app/models/block.rb
class Block < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :get_current_user, :isSignedIn?, :require_login

	def require_login
		redirect_to login_path unless isSignedIn?
	end

	def get_current_user
		if session[:user_id]
			User.find(session[:user_id])
		else
			nil
		end
	end

	def isSignedIn?
		if get_current_user
			true
		end
	end

	def landingPage
		redirect_to inbox_path
	end

end

app/controllers/friend_controller.rb
class FriendController < ApplicationController
	before_action :require_login, only: [:list, :blockList, :add, :block]
	def list
		@curren_user = get_current_user
		@user_list = User.all # I don't know how to query with 3 tables
		@friend_list = []
		Friend.where(owner: @curren_user.id).each_with_index do |friend, index| #is there better way?
			@friend_list[index] = User.find(friend.friend)
		end
	end

	def blockList
		@curren_user = get_current_user
		@block_list = []
		Block.where(blocker: @curren_user.id).each_with_index do |block, index| #is there better way?
			@block_list[index] = User.find(block.blocked)
		end
	end

	def add
		@curren_user = get_current_user
		@friend = Friend.new
		@friend.owner = @curren_user.id
		@friend.friend = params["id"]
		@friend.save

		Block.where("blocker = ? and blocked = ?", @curren_user.id, params["id"])
		if(@block_list.length == 1)
			@block_list[0].destroy
		end

		redirect_to friend_list_path
	end

	def addByPost
		@curren_user = get_current_user
		@friend = Friend.new
		@friend.owner = @curren_user.id
		@friend.friend = params[:friend][:friend]
		@friend.save

		@block_list = Block.where("blocker = ? and blocked = ?", @curren_user.id, params["id"])
		if(@block_list.length == 1)
			@block_list[0].destroy
		end


		redirect_to friend_list_path
	end

	def block
		@curren_user = get_current_user
		@block = Block.new
		@block.blocker = @curren_user.id
		@block.blocked = params["id"]
		@block.save

		@friend_list = Friend.where("owner = ? and friend = ?", @curren_user.id, params["id"])
		if(@friend_list.length == 1)
			@friend_list[0].destroy
		end

		redirect_to friend_list_path
	end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
	before_action :require_login, only: [:inbox, :sendMessage, :detail] # What 's happen if I want to check login all pages

	def inbox
		@curren_user = get_current_user # can it be a global variable?
		@list_message = Message.where("receiver = ? or sender = ?", @curren_user.id, @curren_user.id).sort do|x,y| y.created_at<=>x.created_at end # is there another way
	end

	def detail
		@curren_user = get_current_user
		@message = Message.find(params["id"])
		@sender = User.find(@message.sender)
		if @sender.id != @curren_user.id
			@message.isRead = true
			@message.save
		end
	end

	def sendMessage
		@curren_user = get_current_user
		@friend_list = []
		Friend.where(owner: @curren_user.id).each_with_index do |friend, index| #is there better way?
			@friend_list[index] = User.find(friend.friend)
		end
	end

	def sendTo
		@curren_user = get_current_user
		params[:message][:receiver].each do |receiver| # I got a blank "" value in here
			unless (receiver.blank?)
				@message = Message.new()
				@message.sender = @curren_user.id
				@message.receiver = receiver
				@message.body = params[:message][:body]
				@message.isRead = false
				@message.save
			end
		end
		redirect_to inbox_path
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    if isSignedIn?
      landingPage
    end
  end

  def create
  	@user = User.find_by_email(params[:user]["email"])
  	if(@user && @user.authenticate(params[:user]["password"]))
  		flash[:success] = "Welcome back, #{params[:user][:name]}"
      session[:user_id] = @user.id
      landingPage
  	else
  		flash[:error] = "Incorrect username or password, please try again"
      session[:user_id] = nil
      redirect_to login_path
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    if isSignedIn?
      landingPage
    end
  end

  def signup
  	@user = User.new(params[:user].permit(:name, :email, :password, :avatar))
    if (@user.save)
      flash[:success] = "Your account is created, please login!"
    	redirect_to login_path
  	else
  		flash[:error] = "There are some errors, please try again"
      render "show"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/friend/blockList.html.erb
<div class="image-background">
	<div class="container">
		<div class="menu">
			<div class="current_user">
				<img src="<%= @curren_user.avatar %>?<%= @curren_user.name %>" />
				<span><%= @curren_user.name %></span>
				<span class="email"><%= @curren_user.email %></span>
			</div>
			<ul>
				<li><a href="<%= inbox_path %>?asd" class="button"><i class="fa fa-bars"></i>Inbox</a></li>
				<li><a href="<%= send_path %>" class="button"><i class="fa fa-paper-plane"></i>Send message</a></li>
				<li class="line"></li>
				<li><a href="<%= friend_list_path %>" class="button"><i class="fa fa-users"></i>Friend list</a></li>
				<li><a class="button actived"><i class="fa fa-user-times"></i>Block list</a></li>
				<li class="line"></li>
				<li><a href="<%= signout_path %>" class="button signout"><i class="fa fa-sign-out"></i>Sign out</a></li>
			</ul>
		</div>
		<div class="contents friend_list">
			<ul class="list block">
				<% @block_list.each do |block| %>
				<li>
					<img src="<%= block.avatar %>?<%= block.name %>" />
					<div class="info">
						<p><%= block.name %></p>
						<p><%= block.email %></p>
						<ul class="extra">
							<li><a href="/friend/add/<%= block.id %>" class="add"><i class="fa fa-user-plus"></i>Add</a></li>
						</ul>
					</div>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/friend/list.html.erb
<div class="image-background">
	<div class="container">
		<div class="menu">
			<div class="current_user">
				<img src="<%= @curren_user.avatar %>?<%= @curren_user.name %>" />
				<span><%= @curren_user.name %></span>
				<span class="email"><%= @curren_user.email %></span>
			</div>
			<ul>
				<li><a href="<%= inbox_path %>" class="button"><i class="fa fa-bars"></i>Inbox</a></li>
				<li><a href="<%= send_path %>" class="button"><i class="fa fa-paper-plane"></i>Send message</a></li>
				<li class="line"></li>
				<li><a class="button actived"><i class="fa fa-users"></i>Friend list</a></li>
				<li><a href="<%= block_list_path %>" class="button"><i class="fa fa-user-times"></i>Block list</a></li>
				<li class="line"></li>
				<li><a href="<%= signout_path %>" class="button signout"><i class="fa fa-sign-out"></i>Sign out</a></li>
			</ul>
		</div>
		<div class="contents friend_list">
			<%= form_for(Friend.new, url: friend_add_path, html: {class: "invite-form"}) do |f| %>
				<%= f.select :friend, options_for_select(@user_list.map{ |user_list| [user_list.email, user_list.id] }) %>
				<%= f.submit "Invite" %>
			<% end %>

			<ul class="list">
				<% @friend_list.each do |friend| %>
				<li>
					<img src="<%= friend.avatar %>?<%= friend.name %>" />
					<div class="info">
						<p><%= friend.name %></p>
						<p><%= friend.email %></p>
						<ul class="extra">
							<li><a href="/friend/block/<%= friend.id %>" class="block"><i class="fa fa-user-times"></i>Block</a></li>
						</ul>
					</div>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Week2Assignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="message <%= flash.keys[0] %>">
	<p><%= flash[flash.keys[0]] %></p>
</div>

<%= yield %>

</body>
</html>

app/views/message/detail.html.erb
<div class="image-background">
	<div class="container">
		<div class="menu">
			<div class="current_user">
				<img src="<%= @curren_user.avatar %>" />
				<span><%= @curren_user.name %></span>
				<span class="email"><%= @curren_user.email %></span>
			</div>
			<ul>
				<li><a href="<%= inbox_path %>" class="button"><i class="fa fa-bars"></i>Inbox</a></li>
				<li><a href="<%= send_path %>" class="button"><i class="fa fa-paper-plane"></i>Send message</a></li>
				<li class="line"></li>
				<li><a href="<%= friend_list_path %>" class="button"><i class="fa fa-users"></i>Friend list</a></li>
				<li><a href="<%= block_list_path %>" class="button"><i class="fa fa-user-times"></i>Block list</a></li>
				<li class="line"></li>
				<li><a href="<%= signout_path %>" class="button signout"><i class="fa fa-sign-out"></i>Sign out</a></li>
			</ul>
		</div>
		<div class="contents message_detail">
			<div class="detail">
				<div class="user">
					<% 
						if @sender.id == @curren_user.id
							receiver = User.find(@message.receiver)
					%>
						<span>To: </span>
						<img src="<%= @sender.avatar %>?<%= receiver.name %>" />
						<span><%= receiver.name %> - <%= receiver.email %></span>
					<% else %>
						<span>From: </span>
						<img src="<%= @sender.avatar %>" />
						<span><%= @sender.name %> - <%= @sender.email %></span>
						<ul class="extra">
							<%
								friends = Friend.where(owner: @curren_user.id).pluck(:friend)
								unless friends.include?(@sender.id)
							%>
								<li><a href="/friend/add/<%= @sender.id %>" class="add"><i class="fa fa-user-plus"></i>Add this friend</a></li>
							<% end %>
							<li><a href="/friend/block/<%= @sender.id %>" class="block"><i class="fa fa-user-times"></i>Block this user</a></li>
						</ul>
					<% end %>
				</div>
				<div class="message_detail">
					<%= @message.body %>
				</div>
				<div class="info">
					<% if @sender.id != @curren_user.id %>
						<a><i class="fa fa-reply"></i>Reply</a>
					<% end %>
						<span class="time"><%= @message.created_at.strftime("%I:%M %p %A, %B %d %Y") %></span>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/message/inbox.html.erb
<div class="image-background">
	<div class="container">
		<div class="menu">
			<div class="current_user">
				<img src="<%= @curren_user.avatar %>" />
				<span><%= @curren_user.name %></span>
				<span class="email"><%= @curren_user.email %></span>
			</div>
			<ul>
				<li><a class="button actived"><i class="fa fa-bars"></i>Inbox</a></li>
				<li><a href="<%= send_path %>" class="button"><i class="fa fa-paper-plane"></i>Send message</a></li>
				<li class="line"></li>
				<li><a href="<%= friend_list_path %>" class="button"><i class="fa fa-users"></i>Friend list</a></li>
				<li><a href="<%= block_list_path %>" class="button"><i class="fa fa-user-times"></i>Block list</a></li>
				<li class="line"></li>
				<li><a href="<%= signout_path %>" class="button signout"><i class="fa fa-sign-out"></i>Sign out</a></li>
			</ul>
		</div>
		<div class="contents message_list">
			<ul>
				<% 
				@list_message .each do |message|
					sender = User.find(message.sender)

					blockeds = Block.where(blocker: @curren_user.id).pluck(:blocked)
					unless blockeds.include?(sender.id)
				%>
					<li>
						<% 
							if message.sender == @curren_user.id 
								receiver = User.find(message.receiver)
						%>
							<a class="sender" href="inbox/<%= message.id %>">
								<span>To: </span> 
								<img src="<%= receiver.avatar %>?<%= receiver.name %>" />
								<span><%= receiver.name %> - <%= receiver.email %></span>
								<span class="time"><%= message.created_at.strftime("%I:%M %p %A, %B %d %Y") %></span>
							</a>
							<% else %>
							<a <% if message.isRead%>class="disabled"<% else %> href="inbox/<%= message.id %>" <% end %> >
								<span>From: </span> 
								<img src="<%= sender.avatar %>?<%= sender.name %>" />
								<span><%= sender.name %> - <%= sender.email %></span>
								<span class="time"><%= message.created_at.strftime("%I:%M %p %A, %B %d %Y") %></span>
							</a>
							<% end %>
					</li>
					<% end %>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/message/sendMessage.html.erb
<div class="image-background">
	<div class="container">
		<div class="menu">
			<div class="current_user">
				<img src="<%= @curren_user.avatar %>" />
				<span><%= @curren_user.name %></span>
				<span class="email"><%= @curren_user.email %></span>
			</div>
			<ul>
				<li><a href="<%= inbox_path %>" class="button"><i class="fa fa-bars"></i>Inbox</a></li>
				<li><a class="button actived"><i class="fa fa-paper-plane"></i>Send message</a></li>
				<li class="line"></li>
				<li><a href="<%= friend_list_path %>" class="button"><i class="fa fa-users"></i>Friend list</a></li>
				<li><a href="<%= block_list_path %>" class="button"><i class="fa fa-user-times"></i>Block list</a></li>
				<li class="line"></li>
				<li><a href="<%= signout_path %>" class="button signout"><i class="fa fa-sign-out"></i>Sign out</a></li>
			</ul>
		</div>
		<div class="contents">
			<%= form_for(Message.new, url: send_path, html: {class: "send-form"}) do |f| %>
				<fieldset>
					<label>To: </label>
					<%= f.select :receiver, options_for_select(@friend_list.map{ |friend| [friend.email, friend.id] }), {}, {:multiple => true} %>
				</fieldset>
				<fieldset>
					<label>Message: </label>
					<%= f.text_area "body", placeholder: "Your message" %>
				</fieldset>
				<%= f.submit "Send" %>
			<% end %>
		</div>
	</div>
</div>

app/views/session/new.html.erb
<div class="image-background">
	<%= form_for(User.new, url: login_path, html: {class: "user-form"}) do |f| %>
		<h3>CoderChat</h3>
		<fieldset>
			<i class="fa fa-envelope"></i>
			<%= f.text_field 'email', placeholder: 'Your E-mail' %>
		</fieldset>
		<fieldset>
			<i class="fa fa-lock"></i>
			<%= f.password_field "password", placeholder: "Your password" %>
		</fieldset>
		<%= f.submit "Sign in" %>
		<p>You don't have an account</p>
		<a href="<%= signup_path %>" class="button">Sign up</a>
	<% end %>
</div>

app/views/user/show.html.erb
<div class="image-background">
	<%= form_for(User.new, url: signup_path, html: {class: "user-form"}) do |f| %>
		<h3>CoderChat</h3>
		<fieldset>
			<i class="fa fa-user"></i>
			<%= f.text_field 'name', placeholder: 'Your name' %>
		</fieldset>
		<fieldset>
			<i class="fa fa-envelope"></i>
			<%= f.text_field 'email', placeholder: 'Your E-mail' %>
		</fieldset>
		<fieldset>
			<i class="fa fa-lock"></i>
			<%= f.password_field "password", placeholder: "Your password" %>
		</fieldset>
		<fieldset>
			<i class="fa fa-lock"></i>
			<%= f.password_field "password_confirmation", placeholder: "Confirm your password" %>
		</fieldset>
		<%= f.hidden_field "avatar", value: "http://placeimg.com/100/100/people" %>
		<%= f.submit "Sign up" %>
		<p>You have an account already</p>
		<a href="<%= login_path %>" class="button">Sign in</a>
	<% end %>
</div>